### ISSUE TITLE
TypeError: Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by realrecordzLab** [javascript-obfuscator/webpack-obfuscator#101]
Trying to use this plugin with vue and electron but if try to use the `electron:serve` the console will log this error 

```
vue-cli-service electron:serve
 INFO  Starting development server...

<s> [webpack.Progress] 0% compiling

 ERROR  TypeError: Cannot read property 'tap' of undefined
TypeError: Cannot read property 'tap' of undefined
    at /Users/lab/Sites/fil/electron-app/node_modules/webpack-obfuscator/dist/plugin/index.js:25:45
    at SyncHook.eval (eval at create (/Users/lab/Sites/fil/electron-app/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:19:1)
    at SyncHook.lazyCompileHook (/Users/lab/Sites/fil/electron-app/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/lab/Sites/fil/electron-app/node_modules/webpack/lib/Compiler.js:631:26)
    at /Users/lab/Sites/fil/electron-app/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lab/Sites/fil/electron-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/lab/Sites/fil/electron-app/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/lab/Sites/fil/electron-app/node_modules/webpack/lib/Compiler.js:662:28)
    at /Users/lab/Sites/fil/electron-app/node_modules/webpack/lib/Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lab/Sites/fil/electron-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/lab/Sites/fil/electron-app/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._go (/Users/lab/Sites/fil/electron-app/node_modules/webpack/lib/Watching.js:41:32)
    at /Users/lab/Sites/fil/electron-app/node_modules/webpack/lib/Watching.js:33:9
    at Compiler.readRecords (/Users/lab/Sites/fil/electron-app/node_modules/webpack/lib/Compiler.js:529:11)
    at new Watching (/Users/lab/Sites/fil/electron-app/node_modules/webpack/lib/Watching.js:30:17)
    at Compiler.watch (/Users/lab/Sites/fil/electron-app/node_modules/webpack/lib/Compiler.js:244:10)
```

This is the `vue.config.js` file I'm using
```
const WebpackObfuscator = require('webpack-obfuscator');

module.exports = {
  configureWebpack: {
    plugins: [
      new WebpackObfuscator({
        rotateStringArray: true,
        debugProtection: true,
        disableConsoleOutput: true,
        selfDefending: true,
        stringArrayWrappersType: 'function'
      })
    ]
  },
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
        appId: "com.realrecordzlab.fil",
        copyright: "Copyright © 2020 realrecordzLab",
        artifactName: "${name}-${version}-${os}.${ext}",
        asar: true,
        mac: {
          target: {
            target: "dmg"
          },
          icon: "build/icon.icns",
        },
        win: {
          icon: "build/icon.icns"
        }
      },
      outputDir: "build",
      preload: "src/preload.js"
    }
  }
}
```

Is possible to fix this problem?

**Comment by cnscorpions** [comment]
also faced with it, any workaroud 😂

**Comment by cnscorpions** [comment]
it works only for Webpack@5

**Comment by sanex3339** [comment]
Hi. For webpack@4 use latest `webpack-obfuscator@2.6.0`
For webpack@5 - 3.1.0

**Comment by cnscorpions** [comment]
@sanex3339 , thank you, I will have a try. 😁

**Comment by realrecordzLab** [comment]
Thank you I will try downgrade the library version.

Il giorno lun 14 dic 2020 alle ore 10:03 Gavin Chan <
notifications@github.com> ha scritto:
