### ISSUE TITLE
'Invalid Mapping' Error

### ISSUE THREAD

**Issue by Slapbox** [javascript-obfuscator/webpack-obfuscator#22]
```
C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-map-generator.js:275
        throw new Error('Invalid mapping: ' + JSON.stringify({
              ^
Error: Invalid mapping: {"generated":{"line":1,"column":1429745},"source":"sourceMap","original":{"line":28525,"column":-1094},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-map-generator.js:275:15)
    at SourceMapGenerator_addMapping [as addMapping] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-map-generator.js:105:14)
    at C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:350:15
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:229:11)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_toStringWithSourceMap [as toStringWithSourceMap] (C:\projects\MyProject\node_modules\escodegen-wallaby\node_modules\source-map\lib\source-map\source-node.js:341:10)
    at Object.generate (C:\projects\MyProject\node_modules\escodegen-wallaby\escodegen.js:2762:23)
    at e.value (C:\projects\MyProject\node_modules\javascript-obfuscator\dist\webpack:\src\JavaScriptObfuscatorInternal.ts:129:69)
    at e.value (C:\projects\MyProject\node_modules\javascript-obfuscator\dist\webpack:\src\JavaScriptObfuscatorInternal.ts:92:68)
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn node ENOENT
    at notFoundError (C:\Projects\MyProject\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Projects\MyProject\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Projects\MyProject\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

```

**My Plugins:**
```
  plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'production')
    }),

    new ExtractTextPlugin('style.css'),

    new BundleAnalyzerPlugin({
      analyzerMode: process.env.OPEN_ANALYZER === 'true' ? 'server' : 'disabled',
      openAnalyzer: process.env.OPEN_ANALYZER === 'true'
    }),
    
    new JavaScriptObfuscator({
      disableConsoleOutput: false,
      rotateUnicodeArray: true,
      encodeUnicodeLiterals: true
    }),
```

I'm not using `devtool` to generate sourcemaps. I'm not sure where to begin with debugging this. Any thoughts? Thanks very much for reading.

**Comment by tvpavan** [comment]
+1

**Comment by sanex3339** [comment]
Can you upload minimal working project where i can reproduce this error? It should be prepared project, i should just install dependencies and build it.

**Comment by Slapbox** [comment]
@sanex3339 I can't upload my source code, and I can't even begin to determine how to track down the source of the error, hence reproduce the issue.

If you could give me any advice at all on how to track down the source of the error I'd be happy to provide a repo to reproduce the issue.

**Comment by sanex3339** [comment]
You can replace your source code on any other code on which i can reproduce this error

**Comment by Slapbox** [comment]
@sanex3339 I haven't the slightest clue where the error originates, hence cannot reproduce or debug on my own. I have tried to reproduce the issue with a number of best guesses at what the issue could be, without any luck.

Do you have any idea how I can track this down when it's not giving me a source for the errors? If I can find the error, I'd be happy to produce a package to demonstrate. Thanks for any advice.

**Comment by Slapbox** [comment]
@sanex3339 so I finally revisited this. I manually obfuscated the output javascript using https://github.com/javascript-obfuscator/javascript-obfuscator and it worked without any issues. Do you have any idea how I can prevent the webpack version from relying on sourcemaps? The underlying tool seems to work fine without.

Thanks for any advice you might be able to give.

**Comment by sanex3339** [comment]
Hi. Interesting. I'm not good at webpack plugins, so i need some help with source maps

**Comment by nanki** [comment]
in my case.

#### package.json

```
{
  "name": "ab",
  "version": "1.0.0",
  "scripts": {
    "start": "webpack --config config.js --entry ./ab.js --output-filename output.js"
  },
  "devDependencies": {
    "babel-loader": "^7.1.4",
    "webpack": "^4.1.1",
    "webpack-cli": "^2.0.11",
    "webpack-obfuscator": "^0.14.3"
  }
}
```

#### config.js

```
const JavaScriptObfuscator = require('webpack-obfuscator')

module.exports = {
  plugins: [
    new JavaScriptObfuscator({sourceMap: true})
  ],
  module: {
    rules: [{test: /\.js$/, use: 'babel-loader'}]
  }
}
```

#### ab.js

```
var b = 'b';
var ab = 'a\
' + b;

console.log(ab);
```

```
$ npm start
> ab@1.0.0 start /Users/nanki/ab
> webpack --config config.js --entry ./ab.js --output-filename output.js

(node:95447) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

/Users/nanki/ab/node_modules/escodegen-wallaby/node_modules/source-map/lib/source-map/source-map-generator.js:275
        throw new Error('Invalid mapping: ' + JSON.stringify({
              ^
Error: Invalid mapping: {"generated":{"line":1,"column":1617},"source":"sourceMap","original":{"line":81,"column":-4},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/nanki/ab/node_modules/escodegen-wallaby/node_modules/source-map/lib/source-map/source-map-generator.js:275:15)
    at SourceMapGenerator_addMapping [as addMapping] (/Users/nanki/ab/node_modules/escodegen-wallaby/node_modules/source-map/lib/source-map/source-map-generator.js:105:14)
    at /Users/nanki/ab/node_modules/escodegen-wallaby/node_modules/source-map/lib/source-map/source-node.js:350:15
    at SourceNode_walk [as walk] (/Users/nanki/ab/node_modules/escodegen-wallaby/node_modules/source-map/lib/source-map/source-node.js:229:11)
    at SourceNode_walk [as walk] (/Users/nanki/ab/node_modules/escodegen-wallaby/node_modules/source-map/lib/source-map/source-node.js:225:15)
    at SourceNode_walk [as walk] (/Users/nanki/ab/node_modules/escodegen-wallaby/node_modules/source-map/lib/source-map/source-node.js:225:15)
    at SourceNode_walk [as walk] (/Users/nanki/ab/node_modules/escodegen-wallaby/node_modules/source-map/lib/source-map/source-node.js:225:15)
    at SourceNode_walk [as walk] (/Users/nanki/ab/node_modules/escodegen-wallaby/node_modules/source-map/lib/source-map/source-node.js:225:15)
    at SourceNode_walk [as walk] (/Users/nanki/ab/node_modules/escodegen-wallaby/node_modules/source-map/lib/source-map/source-node.js:225:15)
    at SourceNode_walk [as walk] (/Users/nanki/ab/node_modules/escodegen-wallaby/node_modules/source-map/lib/source-map/source-node.js:225:15)
    at SourceNode_walk [as walk] (/Users/nanki/ab/node_modules/escodegen-wallaby/node_modules/source-map/lib/source-map/source-node.js:225:15)
    at SourceNode_walk [as walk] (/Users/nanki/ab/node_modules/escodegen-wallaby/node_modules/source-map/lib/source-map/source-node.js:225:15)
    at SourceNode_toStringWithSourceMap [as toStringWithSourceMap] (/Users/nanki/ab/node_modules/escodegen-wallaby/node_modules/source-map/lib/source-map/source-node.js:341:10)
    at Object.generate (/Users/nanki/ab/node_modules/escodegen-wallaby/escodegen.js:2782:23)
    at e.value (/Users/nanki/ab/node_modules/javascript-obfuscator/dist/index.js:24:267520)
    at e.value (/Users/nanki/ab/node_modules/javascript-obfuscator/dist/index.js:24:266445)
    at Function.value (/Users/nanki/ab/node_modules/javascript-obfuscator/dist/index.js:24:28815)
    at /Users/nanki/ab/node_modules/webpack-obfuscator/index.js:49:66
    at Array.forEach (<anonymous>)
    at /Users/nanki/ab/node_modules/webpack-obfuscator/index.js:27:23
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/nanki/ab/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/nanki/ab/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.additionalAssets.callAsync.err (/Users/nanki/ab/node_modules/webpack/lib/Compilation.js:943:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/nanki/ab/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/nanki/ab/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeTree.callAsync.err (/Users/nanki/ab/node_modules/webpack/lib/Compilation.js:939:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/nanki/ab/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/nanki/ab/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/Users/nanki/ab/node_modules/webpack/lib/Compilation.js:881:27)
    at hooks.make.callAsync.err (/Users/nanki/ab/node_modules/webpack/lib/Compiler.js:464:17)
    at _err0 (eval at create (/Users/nanki/ab/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (/Users/nanki/ab/node_modules/webpack/lib/Compilation.js:749:12)
    at processModuleDependencies.err (/Users/nanki/ab/node_modules/webpack/lib/Compilation.js:688:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ab@1.0.0 start: `webpack --config config.js --entry ./ab.js --output-filename output.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ab@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nanki/.npm/_logs/2018-03-13T09_51_55_512Z-debug.log
```

**Comment by sanex3339** [comment]
Closed as old. Please try on latest version.
