### ISSUE TITLE
webpack-obfuscator doesn't work with favicons-webpack-plugin

### ISSUE THREAD

**Issue by ezze** [javascript-obfuscator/webpack-obfuscator#28]
Trying to use this awesome obfuscator with my project I was getting [the following error](https://github.com/javascript-obfuscator/webpack-obfuscator/issues/20#issuecomment-361955327):

    /home/ezze/Development/geoport/node_modules/inversify/lib/planning/metadata_reader.js:8
            var compilerGeneratedMetadata = Reflect.getMetadata(METADATA_KEY.PARAM_TYPES, constructorFunc);
                                                    ^
    TypeError: Reflect.getMetadata is not a function
        at MetadataReader.getConstructorMetadata (/home/ezze/Development/geoport/node_modules/inversify/lib/planning/metadata_reader.js:8:49)
        at getTargets (/home/ezze/Development/geoport/node_modules/inversify/lib/planning/reflection_utils.js:15:35)
        at Object.getDependencies (/home/ezze/Development/geoport/node_modules/inversify/lib/planning/reflection_utils.js:10:19)
        at /home/ezze/Development/geoport/node_modules/inversify/lib/planning/planner.js:106:51
        at Array.forEach (<anonymous>)
        at _createSubRequests (/home/ezze/Development/geoport/node_modules/inversify/lib/planning/planner.js:94:20)
        at Object.plan (/home/ezze/Development/geoport/node_modules/inversify/lib/planning/planner.js:129:9)
        at /home/ezze/Development/geoport/node_modules/inversify/lib/container/container.js:243:37
        at Container._get (/home/ezze/Development/geoport/node_modules/inversify/lib/container/container.js:236:44)
        at Container.get (/home/ezze/Development/geoport/node_modules/inversify/lib/container/container.js:195:21)
        at e.value (/home/ezze/Development/geoport/node_modules/javascript-obfuscator/dist/webpack:/src/container/InversifyContainerFacade.ts:126:34)
        at Function.value (/home/ezze/Development/geoport/node_modules/javascript-obfuscator/dist/webpack:/src/JavaScriptObfuscatorFacade.ts:26:17)
        at /home/ezze/Development/geoport/node_modules/webpack-obfuscator/index.js:49:66
        at Array.forEach (<anonymous>)
        at Compilation.<anonymous> (/home/ezze/Development/geoport/node_modules/webpack-obfuscator/index.js:27:23)
        at Compilation.applyPluginsAsyncSeries (/home/ezze/Development/geoport/node_modules/webpack/node_modules/tapable/lib/Tapable.js:206:13)

Finally I narrowed the problem and stated that this one happens when both [favicons-wepback-plugin](https://github.com/jantimon/favicons-webpack-plugin) and obfuscator plugin are used. I use `favicons-webpack-plugin` with [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) and [html-webpack-template](https://github.com/jaketrent/html-webpack-template) this way:

    new HtmlPlugin({
        filename: path.resolve(__dirname, 'dist/index.html'),
        inject: false,
        template: htmlTemplate,
        title: 'RIPI GeoPort',
        meta: [{
            'http-equiv': 'Cache-Control',
            content: 'no-cache, no-store, must-revalidate'
        }, {
            'http-equiv': 'Pragma',
            content: 'no-cache'
        }, {
            'http-equiv': 'Expires',
            content: '0'
        }],
        appMountId: 'container',
        scripts: ['cesium/Cesium.js'],
        minify: {
            collapseWhitespace: NODE_ENV === 'production'
        }
    }),
    new FaviconsWepbackPlugin(
        path.resolve(__dirname, 'src/favicon.png')
    )

What is the reason of this error and is it possible to solve it?

My environment:
Ubuntu 16.04 LTS
Node 8.9.4
Webpack 3.8.1

**Comment by sanex3339** [comment]
Interesting. I'll check it!

**Comment by sanex3339** [comment]
Reproduced it.

**Comment by sanex3339** [comment]
Conflict between https://github.com/rbuckton/reflect-metadata and https://www.npmjs.com/package/harmony-reflect which is dependency of https://github.com/evilebottnawi/favicons

Will look how to solve it on my side.

**Comment by sanex3339** [comment]
So, `harmony-reflect` has different and deprecated `Reflect API`.
https://github.com/tvcutsem/harmony-reflect/blob/master/doc/api.md

I can't just add condition to the loading of `reflect-metadata` like this:
```
if (!global.Reflect) {
    require('reflect-metadata');
}
```

So, current way is to use different plugin to generate favicons.

**Comment by sanex3339** [comment]
Hi. Try to reinstall plugin. `harmony-reflect` just was updating to `1.6.1` version and this bug was fixed.

**Comment by ezze** [comment]
Upgrading `harmony-reflect` from `1.5.1` to `1.6.0` works for me! Thanks a lot for your investigation.
