### ISSUE TITLE
Error: Cannot read property 'ecmaFeatures' of undefined

### ISSUE THREAD

**Issue by cmiltone** [javascript-obfuscator/webpack-obfuscator#35]
`G:\sites\flip-game\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\EspreeFacade.ts:82
            throw new Error(errorMessage);
                  ^
Error: Cannot read property 'ecmaFeatures' of undefined
    at Function.value (G:\sites\flip-game\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\EspreeFacade.ts:82:19)
    at Function.value (G:\sites\flip-game\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\EspreeFacade.ts:44:65)
    at e.value (G:\sites\flip-game\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\JavaScriptObfuscator.ts:154:34)
    at e.value (G:\sites\flip-game\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\JavaScriptObfuscator.ts:135:55)
    at Function.value (G:\sites\flip-game\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\JavaScriptObfuscatorFacade.ts:27:85)
    at G:\sites\flip-game\node_modules\webpack-obfuscator\index.js:49:66
    at Array.forEach (<anonymous>)
    at Compilation.<anonymous> (G:\sites\flip-game\node_modules\webpack-obfuscator\index.js:27:23)
    at next (G:\sites\flip-game\node_modules\tapable\lib\Tapable.js:204:14)
    at G:\sites\flip-game\node_modules\uglifyjs-webpack-plugin\dist\index.js:266:11
    at step (G:\sites\flip-game\node_modules\uglifyjs-webpack-plugin\dist\uglify\index.js:90:11)
    at done (G:\sites\flip-game\node_modules\uglifyjs-webpack-plugin\dist\uglify\index.js:99:22)
    at G:\sites\flip-game\node_modules\uglifyjs-webpack-plugin\dist\uglify\index.js:105:15
    at G:\sites\flip-game\node_modules\worker-farm\lib\farm.js:191:19
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flip-game@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flip-game@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hp\AppData\Roaming\npm-cache\_logs\2018-05-05T18_46_22_525Z-debug.log`

Trying to obfuscate Vuejs code. Added the plugin to webpack.

Searched a lot for the solution. could not find any

**Comment by cafe4it** [comment]
remove eslint, it work

**Comment by cmiltone** [comment]
Thanks for your feedback @cafe4it, removing eslint got rid off the errors(although I need eslint to be able to lint the code). Could you know why I'm getting this error? I did try using the obfuscator-loader (https://github.com/javascript-obfuscator/obfuscator-loader) it seems better only that it 'clashes' with babel-loader.

**Comment by cafe4it** [comment]
At first, I was like you. Then I do not understand how I did it successfully (GG Translate :))
package.json

>  "dependencies": {
    "vue": "^2.3.3",
    "axios": "^0.16.1",
    "vue-electron": "^1.0.6",
    "vue-router": "^2.5.3",
    "vuex": "^2.3.1"
  },
  "devDependencies": {
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.0",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.24.1",
    "babili-webpack-plugin": "^0.1.2",
    "cfonts": "^1.1.3",
    "chalk": "^2.1.0",
    "copy-webpack-plugin": "^4.0.1",
    "cross-env": "^5.0.5",
    "css-loader": "^0.28.4",
    "del": "^3.0.0",
    "devtron": "^1.4.0",
    "electron": "^1.7.5",
    "electron-debug": "^1.4.0",
    "electron-devtools-installer": "^2.2.0",
    "electron-builder": "^19.19.1",
    "babel-eslint": "^7.2.3",
    "eslint": "^4.4.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-html": "^3.1.1",
    "eslint-config-standard": "^10.2.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.1.1",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^3.0.1",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^0.11.2",
    "html-webpack-plugin": "^2.30.1",
    "multispinner": "^0.2.1",
    "node-loader": "^0.6.0",
    "style-loader": "^0.18.2",
    "url-loader": "^0.5.9",
    "vue-html-loader": "^1.2.4",
    "vue-loader": "^13.0.5",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.4.2",
    "webpack": "^3.5.2",
    "webpack-dev-server": "^2.7.1",
    "webpack-hot-middleware": "^2.18.2",
    "webpack-obfuscator": "^0.16.0"
  }

.eslintrc.js

> module.exports = {
  root: true,
  parser: 'babel-eslint',
  parserOptions: {
    sourceType: 'module'
  },
  env: {
    browser: true,
    node: true
  },
  extends: 'standard',
  globals: {
    __static: true
  },
  plugins: [
    'html'
  ],
  'rules': {
    // allow paren-less arrow functions
    'arrow-parens': 0,
    // allow async-await
    'generator-star-spacing': 0,
    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0
  }
}

**Comment by sanex3339** [comment]
Hi. Can i close this issue?

**Comment by cmiltone** [comment]
Hi @sanex3339, you could close even though I've not understood why It throws this error hence I'm unable to use the plugin in webpack.
Resorted to creating script to call obfuscate method of javascript-obfuscator to obfuscate all js code (after build) in specified dir.

**Comment by diaevd** [comment]
I have the same error with standard vue-cli webpack configuration:

```
.(node:22354) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
⠇  Building for production...(node:22354) UnhandledPromiseRejectionWarning: Error: Cannot read property 'ecmaFeatures' of undefined
    at Function.value (/home/diabolo/src/Vue/tt/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFacade.ts:82:19)
    at Function.value (/home/diabolo/src/Vue/tt/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFacade.ts:44:65)
    at e.value (/home/diabolo/src/Vue/tt/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:154:34)
    at e.value (/home/diabolo/src/Vue/tt/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:135:55)
    at Function.value (/home/diabolo/src/Vue/tt/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscatorFacade.ts:27:85)
    at /home/diabolo/src/Vue/tt/node_modules/webpack-obfuscator/index.js:49:66
    at Array.forEach (<anonymous>)
    at /home/diabolo/src/Vue/tt/node_modules/webpack-obfuscator/index.js:27:23
    at _fn0.then._result0 (eval at create (/home/diabolo/src/Vue/tt/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22354) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22354) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I need eslint, but I don't know how i can use it with obfuscator.

**Comment by sanex3339** [comment]
Without obfuscator plugin everything is ok?

**Comment by diaevd** [comment]
Yes, without them everything is ok.

**Comment by sanex3339** [comment]
Interesting.

**Comment by diaevd** [comment]
If use configuration without eslint everything is ok too.

**Comment by sanex3339** [comment]
This error is very popular
https://www.google.com/search?q=Cannot+read+property+%27ecmaFeatures%27+of+undefine&oq=Cannot+read+property+%27ecmaFeatures%27+of+undefine&aqs=chrome..69i57j69i61j35i39j69i61l2.669j0j7&sourceid=chrome&ie=UTF-8

**Comment by diaevd** [comment]
Yes. Sounds like have ecmaFutures in .eslintrc, but a don't have them. I don't understand what i doing wrong

**Comment by shaji-Dev** [comment]
Is there any fix for this guys? I'm still getting the `Error: Cannot read property 'ecmaFeatures' of undefined `when obfuscating in Nodejs grammatically, but works fine in the terminal...
