### ISSUE TITLE
Error with Aurelia/Webpack

### ISSUE THREAD

**Issue by jmdavid** [javascript-obfuscator/webpack-obfuscator#41]
I followed the documentation, when running 'au build --env prod', I get the following error (I replaced real path with PROJECT_ROOT_FOLDER):

TypeError: Cannot read property 'has' of undefined
    at has (PROJECT_ROOT_FOLDER\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\decorators\Initializable.ts:81:43)

**Comment by brockme** [comment]
I'm still seeing this issue- did someone confirm it was resolved?

webpack 4.27.0
webpack-obfuscator 1.2.1
aurelia-cli 1.2.3

PROJECT_ROOT_FOLDER/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/decorators/Initializable.ts:45
            || initializablePropertiesSet.has(propertyName)
                                          ^
TypeError: Cannot read property 'has' of undefined
    at forEach (PROJECT_ROOT_FOLDER/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/decorators/Initializable.ts:45:43)
    at Array.forEach (<anonymous>)
    at wrapTargetMethodsInInitializedCheck (PROJECT_ROOT_FOLDER/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/decorators/Initializable.ts:38:22)
    at PROJECT_ROOT_FOLDER/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/decorators/Initializable.ts:23:9
    at DecorateProperty (PROJECT_ROOT_FOLDER/node_modules/reflect-metadata/Reflect.js:553:33)
    at Object.decorate (PROJECT_ROOT_FOLDER/node_modules/reflect-metadata/Reflect.js:123:24)
    at __decorate (PROJECT_ROOT_FOLDER/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/custom-code-helpers/console-output/group/ConsoleOutputCodeHelperGroup.ts:4:92)
    at Object.call (PROJECT_ROOT_FOLDER/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/custom-code-helpers/console-output/group/ConsoleOutputCodeHelperGroup.ts:78:1)
    at r (PROJECT_ROOT_FOLDER/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/webpack/bootstrap:19:22)
    at Object.call (PROJECT_ROOT_FOLDER/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/container/modules/custom-code-helpers/CustomCodeHelpersModule.ts:9:40)
    at r (PROJECT_ROOT_FOLDER/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/webpack/bootstrap:19:22)
    at Object.call (PROJECT_ROOT_FOLDER/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/container/InversifyContainerFacade.ts:10:35)
    at r (PROJECT_ROOT_FOLDER/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/webpack/bootstrap:19:22)
    at Object.call (PROJECT_ROOT_FOLDER/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscatorFacade.ts:7:36)
    at r (PROJECT_ROOT_FOLDER/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/webpack/bootstrap:19:22)
    at Object.<anonymous> (PROJECT_ROOT_FOLDER/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/index.ts:3:38)

**Comment by sanex3339** [comment]
What `node` version are you used?

**Comment by brockme** [comment]
I'm using node 10.15.3

Thanks for the quick response! :)

**Comment by sanex3339** [comment]
Could you create a repo with a small reproducible example?

**Comment by brockme** [comment]
I've recreated the bug in a new project here: https://github.com/brockme/aurelia-obfuscator-io-broken
There are a few more relevant details in the readme- but please let me know if there's anymore info I can provide!

**Comment by brockme** [comment]
Hello again!  I'd just like to follow up on this issue in case it got lost in the shuffle.  Let me know if the example I've provided is suitable :)

**Comment by peitschie** [comment]
Turns out this breakage is caused by the `aurelia-polyfills`, which get loaded by the `aurelia-cli` (i.e., `au build`) commands.
The polyfill is only partial, and ends up confusing `reflect-metadata` which attempts to polyfill the remaining Reflect methods. leaving everything in a very broken state.

Most noticeable is that `Reflect.defineMetadata` is supplied by `aurelia-polyfills`, but `Reflect.getMetadata` is defined by `reflect-metadata`... meaning you can't read the value you set!

I don't have a real fix, but I can get this plugin to work if I add the line `require('reflect-metadata')` to the top of the imported `aurelia-polyfills` file.

Nasty little thing to solve though!
