### ISSUE TITLE
Don't work with webpack chain

### ISSUE THREAD

**Issue by gallofeliz** [javascript-obfuscator/webpack-obfuscator#45]
Hi all,

I have used obfuscator directly on files generated by webpack and it works well.

I use a Vue-cli configuration. I configure this plugin : 

```
module.exports = {
  chainWebpack: config => {
    var JavaScriptObfuscator = require('webpack-obfuscator');
    config.plugin('obsfuscation').use(JavaScriptObfuscator, [{}, []])
  }
}
```
When I do a NPM RUN BUILD, I have this error : 

```
⠴  Building for production...
/my-project/node_modules/webpack-obfuscator/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFacade.ts:82
            throw new Error(errorMessage);
                  ^
Error: Cannot read property 'ecmaFeatures' of undefined
    at Function.value (/my-project/node_modules/webpack-obfuscator/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFacade.ts:82:19)
    at Function.processParsingError (/my-project/node_modules/webpack-obfuscator/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFacade.ts:44:46)
    at e.parse (/my-project/node_modules/webpack-obfuscator/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:154:29)
    at e.parseCode (/my-project/node_modules/webpack-obfuscator/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:135:46)
    at Function.obfuscate (/my-project/node_modules/webpack-obfuscator/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscatorFacade.ts:31:70)
    at /my-project/node_modules/webpack-obfuscator/index.js:49:66
    at Array.forEach (<anonymous>)
    at /my-project/node_modules/webpack-obfuscator/index.js:27:23
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/my-project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/my-project/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.additionalAssets.callAsync.err (/my-project/node_modules/webpack/lib/Compilation.js:1280:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/my-project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/my-project/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeTree.callAsync.err (/my-project/node_modules/webpack/lib/Compilation.js:1276:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/my-project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/my-project/node_modules/tapable/lib/Hook.js:35:21)
```

Do you have an idea ?

Thanks,
Regards,

**Comment by gallofeliz** [comment]
Fixed with https://github.com/javascript-obfuscator/webpack-obfuscator/issues/35#issuecomment-425491007

Understandable ...

**Comment by gallofeliz** [comment]
Not really fixed. It produces randomly.
