### ISSUE TITLE
TypeError: Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by renatodolza** [javascript-obfuscator/webpack-obfuscator#55]
Soon after run build this message appears, can anyone help me?

```
/Users/***/Documents/www/myapp/node_modules/webpack-obfuscator/dist/index.js:22
        compiler.hooks.emit.tap(pluginName, (compilation) => {
                      ^

TypeError: Cannot read property 'emit' of undefined
    at WebpackObfuscator.apply (/Users/***/Documents/www/myapp/node_modules/webpack-obfuscator/dist/index.js:22:23)
    at Compiler.apply (/Users/***/Documents/www/myapp/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/***/Documents/www/myapp/node_modules/webpack/lib/webpack.js:33:19)
    at err (/Users/***/Documents/www/myapp/build/build.js:19:3)
    at next (/Users/***/Documents/www/myapp/node_modules/rimraf/rimraf.js:75:7)
    at FSReqWrap.CB [as oncomplete] (/Users/***/Documents/www/myapp/node_modules/rimraf/rimraf.js:111:9)
```

**Comment by nmandrescu** [comment]
I saw the same error when I used directly the latest "webpack-obfuscator", but it wasn't compatible with "webpack" itself. I located an older version that works. In some cases other plugins may also interfere.

**Comment by saaiful** [comment]
> I saw the same error when I used directly the latest "webpack-obfuscator", but it wasn't compatible with "webpack" itself. I located an older version that works. In some cases other plugins may also interfere.

Same for me, new version is the issue.

**Comment by sanex3339** [comment]
What webpack version did you use?

**Comment by sanex3339** [comment]
Latest version requires webpack 4+ version. I released new version and added webpack 4.3.0+ to peerDependencies

**Comment by saaiful** [comment]
> What webpack version did you use?

My project was based on laravel-mix@1, after checking I found it was using "webpack": "^3.0.0"

**Comment by langjinren** [comment]
cannot install webpack-obfuscator@0.17.3

**Comment by zamotkin** [comment]
Guys, do you still have this bug in 0.18.7 release?

**Comment by sanex3339** [comment]
Closed as old. Fell free to create a new issue.
