### ISSUE TITLE
Cannot read property 'sourceAndMap' of undefined

### ISSUE THREAD

**Issue by bigfacewo** [javascript-obfuscator/webpack-obfuscator#61]
Use webpack-obfuscator in vue-cli3.
When running, the error is reported as follows:
```
TypeError: Cannot read property 'sourceAndMap' of undefined
    at WebpackObfuscator.extractSourceAndSourceMap (C:\workspace\uniplore_idis\node_modules\webpack-obfuscator\dist\index.js:49:19)
    at chunk.files.forEach (C:\workspace\uniplore_idis\node_modules\webpack-obfuscator\dist\index.js:29:66)
    at Array.forEach (<anonymous>)
    at compilation.chunks.forEach.chunk (C:\workspace\uniplore_idis\node_modules\webpack-obfuscator\dist\index.js:24:29)
    at Array.forEach (<anonymous>)
    at compiler.hooks.emit.tap (C:\workspace\uniplore_idis\node_modules\webpack-obfuscator\dist\index.js:23:32)
    at _next2 (eval at create (C:\workspace\uniplore_idis\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:26:1)
    at _err2 (eval at create (C:\workspace\uniplore_idis\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:44:1)
    at callback (C:\workspace\uniplore_idis\node_modules\copy-webpack-plugin\dist\index.js:77:17)
    at C:\workspace\uniplore_idis\node_modules\copy-webpack-plugin\dist\index.js:118:24
```
I use it like this:
```
new JavaScriptObfuscator({})
```
Does anyone know what caused this?

**Comment by zamotkin** [comment]
Fixed in 0.18.3
