### ISSUE TITLE
Dynamic import cannot be used with webpack loader

### ISSUE THREAD

**Issue by sxzz** [javascript-obfuscator/webpack-obfuscator#87]
Code: 
```javascript

// index.js
async function main() {
  const mod = await import("./module");
  console.log(mod);
}
main();

// module.js
export const text = "Hello World";
```

Error:
```
ERROR in ./src/index.js
Module build failed (from (webpack)-obfuscator/dist/loader/index.js):
Error: SyntaxError: Unexpected token (2:20)
    at Function.parseCode (/Users/kevin/projects/webpack-obfuscator-demo/node_modules/webpack-obfuscator/dist/loader/index.js:63:23)
    at Function.getCommentedSource (/Users/kevin/projects/webpack-obfuscator-demo/node_modules/webpack-obfuscator/dist/loader/index.js:31:55)
    at Object.Loader (/Users/kevin/projects/webpack-obfuscator-demo/node_modules/webpack-obfuscator/dist/loader/index.js:84:63)
```

Webpack Config:
```javascript
const path = require("path");
const WebpackObfuscator = require("webpack-obfuscator");

module.exports = {
  mode: "production",
  module: {
    rules: [
      {
        test: /\.js$/,
        include: [path.resolve(".", "src")],
        enforce: "post",
        use: {
          loader: WebpackObfuscator.loader,
          options: {
            rotateStringArray: true,
          },
        },
      },
    ],
  },
};
```

**Comment by sanex3339** [comment]
Hi. Try `webpack-obfuscator@1.10.1`

**Comment by sxzz** [comment]
It works! Thank you. But there is an other problem. Not compatible with vue

Code:
```javascript
// index.js

import App from "./App.vue";

new Vue({
  render: h => h(App),
  store,
}).$mount("#app");

```

```vue
<!-- App.vue -->
<template>
  <h1>Hello {{ text }}</h1>
</template>

<script>
export default {
  props: {
    text: String,
  },
};
</script>
```

Webpack Config
```javascript
const path = require("path");
const WebpackObfuscator = require("webpack-obfuscator");
const VueLoaderPlugin = require("vue-loader/lib/plugin");

module.exports = {
  mode: "production",
  module: {
    rules: [
      { test: /\.vue$/, use: ["vue-loader"] },
      {
        test: /\.js$/,
        include: [path.resolve(".", "src")],
        enforce: "post",
        use: {
          loader: WebpackObfuscator.loader,
          options: {
            rotateStringArray: true,
          },
        },
      },
    ],
  },
  plugins: [new VueLoaderPlugin()],
};
```

**Comment by sanex3339** [comment]
Try to add `vue-loader` for `.js` files.

```
{
        test: /\.js$/,
        include: [path.resolve(".", "src")],
        enforce: "post",
        use: [
        {
          loader: WebpackObfuscator.loader,
          options: {
            rotateStringArray: true,
          },
        },
       },
       "vue-loader
      ]
```

**Comment by sanex3339** [comment]
Hmm the problem with 
```
export * from 'foo';
```

Obfuscator adds `foo` to the `stringArray`

**Comment by sxzz** [comment]
> Try to add `vue-loader` for `.js` files.
> 
> ```
> {
>         test: /\.js$/,
>         include: [path.resolve(".", "src")],
>         enforce: "post",
>         use: [
>            {
>                loader: WebpackObfuscator.loader,
>                options: {
>                    rotateStringArray: true,
>                },
>           },
>           "vue-loader
>       ]
> }
> ```

It doesn't work. This will make all javascript code to be ignored.

**Comment by sxzz** [comment]
```
export*from_0x556f('0x0');
```
Spaces are removed

**Comment by sanex3339** [comment]
Not only space. Export path cannot be an identifier. Only literal.
```
export * as foo from FOO; // invalid
export * as foo from 'foo'; // valid
```

**Comment by sxzz** [comment]
Yes. Could you fix it please? Thank you. ^_^

**Comment by sanex3339** [comment]
I cannot fix it right now, because `escodegen` does not support `export * as` constructions.
It removes `as foo` part.

**Comment by sanex3339** [comment]
So. I'll fix that literal value moved to the string array. But i cannot fix that `as foo` part was removed from this export because this is `escodegen` problem. I'll try to create the PR to that package, but it may be merged in few weeks or even months

**Comment by sanex3339** [comment]
Issue for `export * as` exports
#710
